# Generated by Django 3.0.4 on 2020-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(verbose_name='song added at')),
                ('added_by', models.CharField(max_length=200)),
                ('track_duration', models.IntegerField()),
                ('track_number', models.IntegerField()),
                ('disc_number', models.IntegerField()),
                ('album_name', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('track_name', models.CharField(max_length=200)),
                ('spotify_uri', models.CharField(max_length=200)),
            ],
        ),
    ]
